class AppStrings {
  AppStrings._();
  static const appName = "NovaTask";
  static const changeStatusToDone = "تغییر وظیفه به انجام شده";
  static const changeStatusTodo = "تغییر وظیفه به انجام نشده";
  static const editTask = "ویرایش وظیفه";
  static const removeTask = "حذف وظیفه";
  static const appVersion = "ورژن 1.0.0";
  static const emptyStateMessage = "هیچ وظیفه ای برای نمایش دادن وجود ندارد!";
  static const categoryNameLabel = "عنوان دسته بندی";
  static const emptyChartsTask = "داده ای جهت نمایش وجود ندارد!";
  static const createNewCategory = "ایجاد دسته بندی جدید";
  static const welcomeGustUser = "سلام دوست من  خوش اومدی.";
  static const homeMessage = "امیدواریم امروز تمام اهدافت رو با موفقیت تیک بزنی!";
  static const lastAddedTask = "جدیدترین وظیفه شما";
  static const viewAll = "مشاهده همه";
  static const todayTaskChartTitle = "کار های امروز شما";
  static const allTaskChartTitle = "همه کارهای شما";
  static const taskDone = "انجام شده";
  static const todoTask = "برای انجام";
  static const errorTitle = "خطا";
  static const nullCategoryErrorMessage = "لطفا یک دسته بندی انتخاب کنید.";
  static const validateCategoryTitleMsg = "لطفا یک نام برای دسته بندی خود وارد کنید";
  static const validateTaskTitleMsg = "لطفا یک نام برای وظیفه خود وارد کنید";
  static const gustUsername = "کاربر مهمان";
  static const searchTaskHint = "کلمه مورد نظر خود را وارد کنید";
  static const createTask = "ایجاد وظیفه جدید";
  static const taskTitleLabel = "عنوان وظیفه";
  static const taskDescription = "توضیحات کوتاه وظیفه";
  static const taskDateLabel = "تاریخ انجام کار";
  static const selectCategory = "انتخاب دسته بندی";
  static const addTask = "اضافه کردن وظیفه جدید";
  static const addNewCategory = "ایجاد دسته بندی جدید";
  static const selectCategoryColor = "انتخاب رنگ پس زمینه دسته بندی";
  static const selectIconCategory = "انتخاب ایکون دسته بندی";
  static const todayTaskListHeader = "لیست کارهای امروز شما";
}